### ISSUE TITLE
Cannot Authenticate via API

### ISSUE THREAD

**Issue by git-anon** [vasilakisfil/rails5_api_tutorial#20]
When I do a fresh clone and run the project I'm able to authenticate through the UI but not the API: 

Request (tried both `username` and `email`)
```
curl --request POST \
  --url http://localhost:3000/api/v1/sessions \
  --header 'cache-control: no-cache' \
  --header 'content-type: application/json' \
  --data '{ "email": "example@railstutorial.org", "password": "foobar" }'
```

Response
```
{
  "errors": [
    {
      "status": 401,
      "title": "Wrong password or username",
      "detail": "Wrong password or username",
      "source": {
        "pointer": "data"
      }
    }
  ]
}
```

**Comment by asa644** [comment]
hey @git-anon! did you figure out the problem? I'm facing the same issue!

**Comment by cmdtstof** [comment]
me also!

**Comment by vasilakisfil** [comment]
Hey folks! The API uses [JSONAPI](http://jsonapi.org/) media type which means it expects slightly different JSON than the.. regular JSON. Specifically in the production server this works:

```
curl --request POST \
  --url https://rails5-api-tutorial.herokuapp.com//api/v1/sessions \
  --header 'cache-control: no-cache' \
  --header 'content-type: application/json' \
  --data '{ "data": {"attributes": {"email": "example@railstutorial.org", "password": "foobar" }}}'
```

So basically you need to wrap your data inside `{ "data": { "attributes": { ... }}` to work.
